name: examen_flutter_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  get_it: ^7.7.0
  provider: ^6.1.3
  json_serializable: ^6.2.0
  build_runner: ^2.1.7
  flutter_bloc: ^8.0.0
  cupertino_icons: ^1.0.6
  soundpool: ^2.4.1 # Asegúrate de usar la última versión

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/ # Incluye todos los archivos que estén directamente en 'assets/' (como la imagen)
    - assets/music/ # Incluye todos los archivos que estén en la subcarpeta 'assets/music/' (como la música)